spring:
  application:
    name: auth-service
  profiles:
    active: ${ACTIVE}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${JWT_SECRET_KEY}

server:
  port: 19095
