server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: product-service-high
          uri: lb://product-service
          predicates:
            - Path=/products/**
            - Weight=product-group, 7
        - id: product-service-low
          uri: lb://product-service
          predicates:
            - Path=/products/**
            - Weight=product-group, 3
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
